In [107]:
import pandas as pd
import os
import re

from datetime import datetime

In [2]:
source_dir = '../source/to_proceed/'
proc_dir = '../output/stage2/'
out_dir = '../output/stage3/'

In [3]:
s1 = set([x[:-4] for x in os.listdir('../source/to_proceed/') if 'pdf' in x])
s2 = set([x[:-4] for x in os.listdir('../output/stage2/') if 'csv' in x])

In [4]:
list(s1.difference(s2))

['Embu_Report',
 'Mbeere_Report',
 'Machakos_Report',
 'MICS4_Pakistan_Punjab_2011_Final_Report_Questionnaires_Appendix',
 'Kenya (Eastern Province)_2008_Moyale',
 'Makueni_Report',
 'Meru_South_Report',
 'Meru_North_Report',
 'Meru_Central_Report',
 'Tunisia 2006 MICS_French',
 'Tharaka_Report',
 'Algeria 2006 MICS_French',
 'Isiolo_Report',
 'Viet Nam 2006 MICS_English',
 'Saint Lucia 2012 MICS_English',
 'Marsabit_Report',
 'Sudan 2010 MICS_English',
 'Kitui_Report',
 'Errata',
 'MICS3_Belize_FinalReport_2006_Eng',
 'MICS3_Bangladesh_FinalReport_2006_Eng',
 'Cuba 2006 MICS_Spanish']

In [5]:
len(list(s1.difference(s2)))

22

In [6]:
all_files = [x for x in os.listdir(proc_dir) if 'csv' in x]

In [285]:
def pushrows(df, col, match, steps=None, from_col=None):
    if not from_col:
        from_col = '0'
        
    df_ = df.copy()
    
    for i, row in df_[df_[col].str.match(match).fillna(False)].iterrows():
        r = row[int(from_col):]
        if steps:
            for _ in range(steps):
                df_.ix[i, from_col:] = r.shift(1)
        else:
            for _ in range(len(row)):
                if pd.isnull(r[-1]):
                    r = r.shift(1)
                else:
                    df_.ix[i, from_col:] = r
                
    return df_

In [ ]:
t = datetime.now()

In [390]:
iii = 45

print(all_files[iii])
print(datetime.now() - t)
t = datetime.now()

Iraq 2006 MICS_English.csv
0:12:18.309966

In [391]:
f = os.path.join(proc_dir, all_files[iii])

data = pd.read_csv(f, dtype=str)

In [392]:
data

,0,1,2,3,4,5,6
0,NUTRITION,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,6,4,Underweight prevalence (moderate and severe) (...,7.6,7.9,percent
2,NaN,NaN,NaN,Stunting prevalence (moderate and severe) (sev...,NaN,NaN,NaN
3,NaN,NaN,NaN,Wasting prevalence (moderate and severe) (severe),NaN,NaN,NaN
4,NaN,NaN,NaN,Timely initiation of breastfeeding Exclusive b...,NaN,NaN,NaN
5,NaN,NaN,NaN,at 12-15 months,NaN,NaN,NaN
6,NaN,NaN,NaN,at 20-23 months,NaN,NaN,NaN
7,NaN,NaN,NaN,Timely complementary feeding rate Frequency of...,NaN,NaN,NaN
8,NaN,NaN,NaN,Iodized salt consumption,NaN,NaN,NaN
9,NaN,NaN,NaN,Vitamin A supplementation (under-fives) Vitami...,NaN,NaN,NaN
10,NaN,NaN,NaN,Low birth weight infants Infants weighed at birth,NaN,NaN,NaN
11,NaN,NaN,NaN,1.4,1.6,percent,NaN
12,Nutritional,7,NaN,21.4,13.1,percent,NaN
13,status,NaN,NaN,7.5,3.9,NaN,NaN
14,NaN,8,NaN,4.8,4.9,percent,NaN
15,NaN,NaN,NaN,1.2,1.2,NaN,NaN
16,NaN,45,NaN,30.6,15.2,percent,NaN
17,NaN,15,NaN,25.1,11.8,percent,NaN
18,NaN,NaN,NaN,NaN,NaN,percent,NaN
19,Breastfeeding,16,NaN,67.6,49.6,percent percent,NaN
20,NaN,NaN,NaN,35.7,32.4,NaN,NaN
21,NaN,17,NaN,51,22,percent,NaN
22,NaN,18,NaN,38,15.2,percent,NaN
23,NaN,19,NaN,31.8,13.6,percent,NaN
24,Salt iodization,41,NaN,28.4,56.8,percent,NaN
25,NaN,42,NaN,2,2.9,percent,NaN
26,Vitamin A,43,NaN,16.1,11.2,percent,NaN
27,Low birth,9,NaN,14.8,14.5,percent,NaN
28,weight,10,NaN,44.9,43.2,percent,NaN
29,CHILD HEALTH,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...
138,NaN,58,NaN,Transition rate to secondary school,78.3,84.4,percent
139,NaN,NaN,NaN,Primary completion rate (gross),80.9,114.3,percent
140,NaN,59,7b,Primary completion rate (net),43.9,49,percent
141,NaN,NaN,NaN,Gender parity index,NaN,NaN,NaN
142,NaN,61,9,Primary school,0.88,0.95,ratio
143,NaN,NaN,NaN,Secondary school,0.75,0.96,ratio
144,Literacy,60,8,Adult literacy rate,65.6,64.2,percent
145,CHILD PROTECTION,NaN,NaN,NaN,NaN,NaN,NaN
146,Birth registration,62,NaN,Birth registration,95,98.5,percent
147,NaN,71,NaN,Child labour,10.7,6.4,percent
148,Child labour,72,NaN,Labourer students,61.5,79.7,percent
149,NaN,73,NaN,Student labourers,9.5,6.4,percent
150,Child discipline,74,NaN,Any psychological/physical punishment,83.7,68.1,percent
151,Early marriage,67,NaN,Marriage before age 15 Marriage before age 18,5.4,6.8,percent percent
152,NaN,NaN,NaN,NaN,22.6,26.1,NaN
153,NaN,68,NaN,Young women aged 15-19 currently married,19,10,percent
154,Topic,Indicator number,Indicator,National,Kurdistan Region,Unit,NaN
155,NaN,MICS MDG,NaN,NaN,NaN,NaN,NaN
156,NaN,69,Spousal age difference Women aged 15-19,25.8,26.5,percent,NaN
157,NaN,NaN,Women aged 20-24,NaN,NaN,NaN,NaN
158,NaN,NaN,Attitudes towards domestic violence Child disa...,NaN,NaN,NaN,NaN
159,NaN,NaN,21.1,21.4,percent,NaN,NaN
160,Domestic violence,100,59.1,36.7,percent,NaN,NaN
161,Disability,101,14.8,18.9,percent,NaN,NaN
162,HIV/AIDS AND ORPHANED CHILDREN,NaN,NaN,NaN,NaN,NaN,NaN
163,NaN,87,NaN,Women who know where to be tested for HIV,6.1,3.4,percent
164,88,NaN,Women who have been tested for HIV,2.8,0.5,percent,NaN
165,Support to,75,NaN,Prevalence of orphans,5.9,5.5,percent
166,orphaned,78,NaN,Children’s living arrangements,2.4,1.5,percent
167,children,77,20,School attendance of orphans versus non-orphans,0.84,1.10,ratio

In [358]:
data['new'] = None

In [393]:
df = pushrows(data, '0', '^[0-9\.\-]+', steps=1)

In [331]:
df = pushrows(df, '1', '[0-9\,]{3,7}')

In [394]:
df.to_csv(os.path.join(out_dir, all_files[iii]), index=False)

In [376]:
df

,0,1,2,3,4
0,CHILD MORTALITY,NaN,NaN,NaN,NaN
1,Early childhood mortalitya,NaN,NaN,NaN,NaN
2,MICS,Description,Value,NaN,NaN
3,Indicator Indicator,NaN,NaN,NaN,NaN
4,NaN,1.1 Neonatal mortality rate,Probability of dying within the ﬁrst month of ...,23,NaN
5,NaN,1.2 MDG 4.2 Infant mortality rate,Probability of dying between birth and the ﬁrs...,32,NaN
6,NaN,1.3 Post-neonatal mortalit...,Diﬀerence between infant and neonatal mortalit...,9,NaN
7,NaN,1.4 Child mortality rate,Probability of dying between the ﬁrst and the ...,8,NaN
8,NaN,1.5 MDG 4.1 Under-ﬁve mortality rate,Probability of dying between birth and the ﬁft...,39,NaN
9,aRates refer to the 5-year period preceding th...,NaN,NaN,NaN,NaN
10,NUTRITION,NaN,NaN,NaN,NaN
11,Nutritional status,NaN,NaN,NaN,NaN
12,MICS,Indicator,Description,Value,NaN
13,Indicator,NaN,NaN,NaN,NaN
14,NaN,2.1a,MDG 1.8,Underweight prevalence,Percentage of children under age 5 who fall below
15,NaN,2.1b,NaN,Moderate and severe,minus two standard deviations (moderate and se...
16,NaN,NaN,Severe,minus three standard deviations (severe),NaN
17,NaN,NaN,NaN,of the median weight for age of the WHO standard,NaN
18,NaN,2.2a,NaN,Stunting prevalence,Percentage of children under age 5 who fall below
19,NaN,2.2b,NaN,Moderate and severe,minus two standard deviations (moderate and se...
20,NaN,NaN,Severe,minus three standard deviations (severe),NaN
21,NaN,NaN,NaN,of the median height for age of the WHO standard,NaN
22,NaN,2.3a,NaN,Wasting prevalence,Percentage of children under age 5 who fall below
23,NaN,2.3b,NaN,Moderate and severe,minus two standard deviations (moderate and se...
24,NaN,NaN,Severe,minus three standard deviations (severe),NaN
25,NaN,NaN,NaN,of the median weight for height of the WHO sta...,NaN
26,NaN,2.4 Overweight prevalence,Percentage of children under age 5 who are abo...,5.3,NaN
27,Breastfeeding and infant feeding,NaN,NaN,NaN,NaN
28,NaN,2.5 Children ever breastfed,Percentage of women with a live birth in the l...,89.0,NaN
29,NaN,2.6 Early initiation of breastfeeding,Percentage of women with a live birth in the l...,49.2,NaN
...,...,...,...,...,...
284,NaN,(b) Men,95.1,NaN,NaN
285,NaN,11.2 Happiness,Percentage of young people age 15-24 years who...,NaN,NaN
286,NaN,very or somewhat happy,NaN,NaN,NaN
287,NaN,(a) Women,93.6,NaN,NaN
288,NaN,(b) Men,92.6,NaN,NaN
289,NaN,11.3 Perception of a better ...,Percentage of young people age 15-24 years who...,81.9,NaN
290,NaN,Women,83.3,NaN,NaN
291,NaN,Men,NaN,NaN,NaN
292,TOBACCO AND ALCOHOL USE,NaN,NaN,NaN,NaN
293,Tobacco use,NaN,NaN,NaN,NaN
294,MICS,Description,Value,NaN,NaN
295,Indicator Indicator,NaN,NaN,NaN,NaN
296,NaN,12.1 Tobacco use,Percentage of people age 15-49 years who smoked,NaN,NaN
297,NaN,"cigarettes, or used smoked or smokeless tobacco",NaN,NaN,NaN
298,NaN,products at any time during the last one month,NaN,NaN,NaN
299,NaN,(a) Women,2.1,NaN,NaN
300,NaN,(b) Men,20.7,NaN,NaN
301,NaN,12.2 Smoking before age 15,Percentage of people age 15-49 years who smoked a,NaN,NaN
302,whole cigarette before age 15,NaN,NaN,NaN,NaN
303,(a) Women,1.7,NaN,NaN,NaN
304,(b) Men,9.4,NaN,NaN,NaN
305,Alcohol use,NaN,NaN,NaN,NaN
306,NaN,12.3 Use of alcohol,Percentage of people age 15-49 years who had a...,NaN,NaN
307,one alcoholic drink at any time during the las...,NaN,NaN,NaN,NaN
308,(a) Women,26.0,NaN,NaN,NaN
309,(b) Men,63.0,NaN,NaN,NaN
310,NaN,12.4 Use of alcohol before ag...,Percentage of people age 15-49 years who had a...,5.1,NaN
311,NaN,Women,NaN,NaN,NaN
312,NaN,Men,NaN,NaN,NaN
313,NaN,20.0,NaN,NaN,NaN

In [377]:
mask = data['0'].str.match('^[0-9\-]+').fillna(False)

In [380]:
for i, r in data[mask].iterrows():
#     print(r[1])
    try:
        idt, name = re.match('^([0-9\-]+\.[A-Za-z0-9]+) ?(.*)', str(r[0]).strip()).groups()
#         data.ix[i, 'idt'] = idt
        if re.match('MDG [0-9\.]+', name):
            mdg, name = re.match('(MDG [0-9\.]+) (.*)', name).groups()
#             name = None
        else:
            mdg = None
        data.ix[i, 'idt'] = str(idt).strip()
        data.ix[i, 'mdg'] = str(mdg).strip()
        data.ix[i, 'name'] = str(name).strip()
        data.ix[i, '0'] = None
        print(idt, mdg, name)
    except AttributeError:
        continue
    except:
        raise

1.1 None Neonatal mortality rate
1.2 MDG 4.2 Infant mortality rate
1.3 None                     Post-neonatal mortality rate
1.4 None Child mortality rate
1.5 MDG 4.1 Under-ﬁve mortality rate
2.1a None
2.1b None
2.2a None
2.2b None
2.3a None
2.3b None
2.4 None Overweight prevalence
2.5 None Children ever breastfed
2.6 None       Early initiation of breastfeeding
2.7 None                    Exclusive breastfeeding under 6 months
2.8 None Predominant
2.9 None                           Continued breastfeeding at 1 year
2.10 None                         Continued breastfeeding at 2 years
2.11 None    Median duration of breastfeeding
2.12 None Age-appropriate
2.13 None                         Introduction of solid, semi- solid or soft foods
2.14 None    Milk feeding frequency for    Percentage of non-breastfed children age 6-23 months who non-breastfed children received at least 2 milk feedings during the previous day
2.15 None Minimum meal frequency
2.16 None Minimum dietary diversity Percentage of children age 6–23 months who received foods
2.17a None Minimum acceptable diet
2.17b None
2.18 None Bottle feeding
2.19 None Iodized salt consumption
2.20 None Low-birthweight infants
2.21 None Infants weighed at birth
3.1 None                    Tuberculosis immunization coverage
3.2 None        Polio immunization coverage
3.3 None Diphtheria, pertussis
3.5 None and tetanus (DPT),
3.6 None Hepatitis B (HepB) and
3.4 None MDG Measles immunization
4.3 None coverage
3.7 None                    Yellow fever immunization coverage
3.8 None        Full immunization coverage
3.9 None     Neonatal tetanus protection
3.10 None    Care-seeking for diarrhoea
3.S1 None                Diarrhoea treatment with oral rehydration salts (ORS)
3.12 None                Diarrhoea treatment with oral rehydration therapy (ORT) and continued feeding
3.13 None          Care-seeking for children with ARI symptoms
3.14 None       Antibiotic treatment for children with ARI symptoms
3.15 None        Use of solid fuels for cooking
3.16a None Household availability
3.16b None            of insecticide-treated nets (ITNs)
3.18 None MDG Children under age 5
6.7 None who slept under an ITN
3.19 None           Population that slept under an ITN
3.20 None Care-seeking for fever
3.21 None           Malaria diagnostics usage
3.22 None MDG Anti-malarial treatment
6.8 None of children under age 5
3.23 None Treatment with
3.24 None             Pregnant women who slept under an ITN
4.2 None Water treatment
4.4 None                    Safe disposal of child’s faeces
4.5 None Place for handwashing
4.6 None                       Availability of soap or other cleansing agent
5.2 None Early childbearing
5.5a None
5.5b None
5.6 None Content of antenatal care
5.8 None Institutional deliveries
5.9 None Caesarean section
5.10 None                    Post-partum stay in health facility
5.11 None                           Post-natal health check for the newborn
5.12 None                           Post-natal health check for the mother
6.1 None                  Attendance to early childhood education
6.2 None Support for learning
6.3 None                   Father’s support for learning
6.4 None                    Mother’s support for learning
6.5 None                        Availability of children’s books
6.6 None Availability of playthings
6.7 None Inadequate care
6.8 None                         Early child development index
7.1 None MDG Literacy rate among
2.3 None young people
7.2 None School readiness
7.3 None             Net intake rate in primary education
7.4 None MDG Primary school net
2.1 None attendance ratio (adjusted)
7.5 None     Secondary school net attendance ratio (adjusted)
7.6 None MDG Children reaching last
2.2 None grade of primary
7.7 None                   Primary completion rate
7.8 None       Transition rate to secondary school
7.9 None MDG Gender parity index
3.1 None (primary school)
7.10 None MDG Gender parity index
3.1 None (secondary school)
8.1 None Birth registration
8.2 None Child labour
8.3 None Violent discipline
8.4 None                        Marriage before age 15
8.5 None                        Marriage before age 18
8.6 None                        Young people age 15- 19 years currently married or in union
8.7 None Polygyny
8.8a None Spousal age diﬀerence
8.8b None
8.12 None        Attitudes towards domestic violence
8.13 None Children’s living arrangements
8.14 None                Prevalence of children with one or both parents dead
8.15 None                 Children with at least one parent living abroad
9.1 None MDG Knowledge about HIV
6.3 None prevention among young people
9.2 None            Knowledge of mother- to-child transmission of HIV
9.3 None             Accepting attitudes towards people living with HIV
9.4 None                     People who know where to be tested for HIV
9.5 None            People who have been tested for HIV and know the results
9.6 None              Sexually active young people who have been tested for HIV and know the results
9.7 None      HIV counselling during antenatal care
9.8 None      HIV testing during antenatal care
9.9 None             Young people who have never had sex
9.10 None               Sex before age 15 among young people
9.11 None          Age-mixing among sexual partners
9.12 None Multiple sexual partnerships
9.13 None         Condom use at last sex among people with multiple sexual partnerships
9.14 None      Sex with non-regular partners
9.15 None MDG Condom use with non-
6.2 None regular partners
10.1 None Exposure to mass
10.2 None Use of computers
10.2 None Use of computers
10.3 None Use of internet
11.1 None Life satisfaction
11.2 None Happiness
11.3 None                   Perception of a better life
12.1 None Tobacco use
12.2 None Smoking before age 15
12.3 None Use of alcohol
12.4 None                  Use of alcohol before age 15
20.0 None

In [381]:
df

,0,1,2,3,4,idt,mdg,name
0,CHILD MORTALITY,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Early childhood mortalitya,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,MICS,Description,Value,NaN,NaN,NaN,NaN,NaN
3,Indicator Indicator,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,1.1 Neonatal mortality rate,Probability of dying within the ﬁrst month of ...,23,NaN,NaN,NaN,NaN
5,NaN,1.2 MDG 4.2 Infant mortality rate,Probability of dying between birth and the ﬁrs...,32,NaN,NaN,NaN,NaN
6,NaN,1.3 Post-neonatal mortalit...,Diﬀerence between infant and neonatal mortalit...,9,NaN,NaN,NaN,NaN
7,NaN,1.4 Child mortality rate,Probability of dying between the ﬁrst and the ...,8,NaN,NaN,NaN,NaN
8,NaN,1.5 MDG 4.1 Under-ﬁve mortality rate,Probability of dying between birth and the ﬁft...,39,NaN,NaN,NaN,NaN
9,aRates refer to the 5-year period preceding th...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NUTRITION,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Nutritional status,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,MICS,Indicator,Description,Value,NaN,NaN,NaN,NaN
13,Indicator,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,2.1a,MDG 1.8,Underweight prevalence,Percentage of children under age 5 who fall below,NaN,NaN,NaN
15,NaN,2.1b,NaN,Moderate and severe,minus two standard deviations (moderate and se...,NaN,NaN,NaN
16,NaN,NaN,Severe,minus three standard deviations (severe),NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,of the median weight for age of the WHO standard,NaN,NaN,NaN,NaN
18,NaN,2.2a,NaN,Stunting prevalence,Percentage of children under age 5 who fall below,NaN,NaN,NaN
19,NaN,2.2b,NaN,Moderate and severe,minus two standard deviations (moderate and se...,NaN,NaN,NaN
20,NaN,NaN,Severe,minus three standard deviations (severe),NaN,NaN,NaN,NaN
21,NaN,NaN,NaN,of the median height for age of the WHO standard,NaN,NaN,NaN,NaN
22,NaN,2.3a,NaN,Wasting prevalence,Percentage of children under age 5 who fall below,NaN,NaN,NaN
23,NaN,2.3b,NaN,Moderate and severe,minus two standard deviations (moderate and se...,NaN,NaN,NaN
24,NaN,NaN,Severe,minus three standard deviations (severe),NaN,NaN,NaN,NaN
25,NaN,NaN,NaN,of the median weight for height of the WHO sta...,NaN,NaN,NaN,NaN
26,NaN,2.4 Overweight prevalence,Percentage of children under age 5 who are abo...,5.3,NaN,NaN,NaN,NaN
27,Breastfeeding and infant feeding,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,NaN,2.5 Children ever breastfed,Percentage of women with a live birth in the l...,89.0,NaN,NaN,NaN,NaN
29,NaN,2.6 Early initiation of breastfeeding,Percentage of women with a live birth in the l...,49.2,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
284,NaN,(b) Men,95.1,NaN,NaN,NaN,NaN,NaN
285,NaN,11.2 Happiness,Percentage of young people age 15-24 years who...,NaN,NaN,NaN,NaN,NaN
286,NaN,very or somewhat happy,NaN,NaN,NaN,NaN,NaN,NaN
287,NaN,(a) Women,93.6,NaN,NaN,NaN,NaN,NaN
288,NaN,(b) Men,92.6,NaN,NaN,NaN,NaN,NaN
289,NaN,11.3 Perception of a better ...,Percentage of young people age 15-24 years who...,81.9,NaN,NaN,NaN,NaN
290,NaN,Women,83.3,NaN,NaN,NaN,NaN,NaN
291,NaN,Men,NaN,NaN,NaN,NaN,NaN,NaN
292,TOBACCO AND ALCOHOL USE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
293,Tobacco use,NaN,NaN,NaN,NaN,NaN,NaN,NaN
294,MICS,Description,Value,NaN,NaN,NaN,NaN,NaN
295,Indicator Indicator,NaN,NaN,NaN,NaN,NaN,NaN,NaN
296,NaN,12.1 Tobacco use,Percentage of people age 15-49 years who smoked,NaN,NaN,NaN,NaN,NaN
297,NaN,"cigarettes, or used smoked or smokeless tobacco",NaN,NaN,NaN,NaN,NaN,NaN
298,NaN,products at any time during the last one month,NaN,NaN,NaN,NaN,NaN,NaN
299,NaN,(a) Women,2.1,NaN,NaN,NaN,NaN,NaN
300,NaN,(b) Men,20.7,NaN,NaN,NaN,NaN,NaN
301,NaN,12.2 Smoking before age 15,Percentage of people age 15-49 years who smoked a,NaN,NaN,NaN,NaN,NaN
302,whole cigarette before age 15,NaN,NaN,NaN,NaN,NaN,NaN,NaN
303,None,1.7,NaN,NaN,NaN,1.7,None,
304,None,9.4,NaN,NaN,NaN,9.4,None,
305,Alcohol use,NaN,NaN,NaN,NaN,NaN,NaN,NaN
306,NaN,12.3 Use of alcohol,Percentage of people age 15-49 years who had a...,NaN,NaN,NaN,NaN,NaN
307,one alcoholic drink at any time during the las...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
308,None,26.0,NaN,NaN,NaN,26.0,None,
309,None,63.0,NaN,NaN,NaN,63.0,None,
310,NaN,12.4 Use of alcohol before ag...,Percentage of people age 15-49 years who had a...,5.1,NaN,NaN,NaN,NaN
311,NaN,Women,NaN,NaN,NaN,NaN,NaN,NaN
312,NaN,Men,NaN,NaN,NaN,NaN,NaN,NaN
313,NaN,20.0,NaN,NaN,NaN,NaN,NaN,NaN

In [383]:
data.to_csv(os.path.join(out_dir, all_files[iii]), index=False)

In [123]:
df = data.copy()
df['new'] = None

df = pushrows(df, '0', '^[0-9\.]+', steps=1)
# df = pushrows(df, '1', '^[0-9\.]+$', from_col='1')

df

,0,1,2,3,4,new
0,Mortalité de la petite enfance,NaN,NaN,NaN,NaN,None
1,Indicateur MICS,Indicateur,Description,ValeurA,NaN,None
2,NaN,1.1,NaN,Taux de mortalité néonatale,Probabilité de décéder dans le premier mois de...,"37,8"
3,NaN,1.2,OMD 4.2,Taux de mortalité Infantile,Probabilité de décéder entre la naissance et l...,"66,5"
4,NaN,1.3,NaN,Taux de mortalité post- néonatale,Différence entre les taux de mortalité infanti...,"28,8"
5,NaN,1.4,NaN,Taux de mortalité juvénile,Probabilité de décéder entre le premier et le ...,"52,2"
6,NaN,1.5,OMD 4.1,Taux de mortalité infanto- juvénile,Probabilité de décéder entre la naissance et l...,"115,2"
7,A La valeur de l’indicateur s’exprime pour 100...,NaN,NaN,NaN,NaN,None
8,Etat Nutritionneli,NaN,NaN,NaN,NaN,None
9,Indicateur MICS,Indicateur,Description,Valeur,NaN,None
10,NaN,2.1a,OMD 1.8,Prévalence de l’insuffisance pondérale,Pourcentage d’enfants de moins de 5 ans qui se...,NaN
11,NaN,2.1b,NaN,Modérée et sévère (-2 SD),en-dessous de moins 2 écarts-type (modéré et s...,"18,0"
12,NaN,NaN,Sévère (-3 SD),en-dessous de moins 3 écarts-type (sévère),"4,7",None
13,NaN,NaN,NaN,de la médiane poids-pour-âge du standard de l’OMS,NaN,None
14,NaN,NaN,NaN,NaN,NaN,None
15,NaN,NaN,NaN,NaN,NaN,None
16,NaN,2.2a,NaN,Prévalence du retard de croissance,Pourcentage d’enfants de moins de 5 ans qui se...,NaN
17,NaN,2.2b,NaN,Modérée et sévère (-2 SD),en-dessous de moins 2 écarts-type (modéré et s...,"34,0"
18,NaN,NaN,Sévère (-3 SD),en-dessous de moins 3 écarts-type (sévère),"12,1",None
19,NaN,NaN,NaN,de la médiane taille-pour-âge du standard de l...,NaN,None
20,NaN,NaN,NaN,NaN,NaN,None
21,NaN,NaN,NaN,NaN,NaN,None
22,NaN,2.3a,NaN,Prévalence de l’émaciation,Pourcentage d’enfants de moins de 5 ans qui se...,"4,5"
23,NaN,2.3b,NaN,Modérée et Sévère (-2 SD),en-dessous de moins 2 écarts-type (modéré et s...,"0,9"
24,NaN,NaN,Sévère (-3 SD),en-dessous de moins 3 écarts-type (sévère),NaN,None
25,NaN,NaN,NaN,de la médiane poids-pour-taille du standard de...,NaN,None
26,NaN,2.3c,NaN,Prévalence de l’obésité,Pourcentage d’enfants de moins de 5 ans qui se...,"1,7"
27,Allaitement et alimentation des enfants,NaN,NaN,NaN,NaN,None
28,Indicateur MICS,Indicateur,Description,Valeur,NaN,None
29,NaN,2.5,Enfants allaités,Pourcentage de femmes qui ont eu une naissance...,"97,2",NaN
...,...,...,...,...,...,...
335,NaN,NaN,NaN,NaN,NaN,None
336,NaN,11.3,Perception d’une vie meilleure,Pourcentage de jeunes de 15-24 ans qui pensent...,NaN,NaN
337,NaN,NaN,Femmes,NaN,"50,1",None
338,NaN,NaN,) Hommes,NaN,"53,9",None
339,NaN,NaN,NaN,NaN,NaN,None
340,NaN,NaN,NaN,NaN,NaN,None
341,Consommation de tabac,NaN,NaN,NaN,NaN,None
342,Indicateur MICS,Indicateur,Description,Valeur,NaN,None
343,NaN,12.1,Consommation de tabac,Pourcentage de personnes de 15-49 ans qui ont ...,NaN,NaN
344,NaN,NaN,Femmes,NaN,"1,8",None
345,NaN,NaN,) Hommes,NaN,"13,8",None
346,NaN,NaN,NaN,NaN,NaN,None
347,NaN,NaN,NaN,NaN,NaN,None
348,NaN,12.2,Consommation de tabac avant 15 ans,Pourcentage de personnes de 15-49 ans qui ont ...,NaN,NaN
349,NaN,NaN,Femmes,NaN,"0,3",None
350,NaN,NaN,) Hommes,NaN,"4,4",None
351,NaN,NaN,NaN,NaN,NaN,None
352,NaN,NaN,NaN,NaN,NaN,None
353,Consommation d’alcool,NaN,NaN,NaN,NaN,None
354,Indicateur MICS,Indicateur,Description,Valeur,NaN,None
355,NaN,12.3,Consommation d’alcool,Pourcentage de personnes de 15-49 ans qui ont ...,NaN,NaN
356,NaN,NaN,Femmes,NaN,"25,5",None
357,NaN,NaN,) Hommes,NaN,"43,7",None
358,NaN,NaN,NaN,NaN,NaN,None
359,NaN,NaN,NaN,NaN,NaN,None
360,NaN,12.4,Consommation d’alcool avant 15 ans,Pourcentage de personnes de 15-49 ans qui ont ...,NaN,NaN
361,NaN,NaN,Femmes,NaN,"19,8",None
362,NaN,NaN,) Hommes,NaN,"22,8",None
363,NaN,NaN,NaN,NaN,NaN,None
364,NaN,NaN,NaN,NaN,NaN,None

In [124]:
df.to_csv(os.path.join(out_dir, all_files[iii]), index=False)